# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-06 19:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170702_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 6, 19, 39, 17, 550977, tzinfo=utc)),
        ),
    ]
