# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-06 20:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170707_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 6, 20, 17, 13, 778243, tzinfo=utc)),
        ),
    ]
