# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-17 05:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20170710_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=3)),
                ('address', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('related', models.CharField(max_length=100)),
                ('entry_year', models.DateField()),
                ('graduation_year', models.DateField()),
                ('level', models.CharField(max_length=10)),
                ('student_type', models.CharField(max_length=1)),
                ('passport_id', models.IntegerField(max_length=12)),
                ('number', models.IntegerField(max_length=9)),
                ('unt', models.IntegerField(max_length=3)),
                ('attestat_number', models.IntegerField(max_length=13)),
                ('attestat_date', models.DateField()),
                ('attestat_type', models.CharField(max_length=12)),
                ('payment', models.CharField(max_length=9)),
                ('certificate_number', models.IntegerField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Father',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 17, 5, 32, 15, 240339, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='applicant',
            name='father',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Father'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='mother',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Mother'),
        ),
    ]
