# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-17 05:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20170917_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='attestat_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='certificate_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='passport_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='unt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 17, 5, 33, 25, 269644, tzinfo=utc)),
        ),
    ]
